[2022-10-14 13:22:15.392] [remoteagent] [info] Extension host agent started.
[2022-10-14 13:22:15.734] [remoteagent] [info] [127.0.0.1][4a462357][ManagementConnection] New connection established.
[2022-10-14 13:22:15.735] [remoteagent] [info] [127.0.0.1][55c06ec9][ExtensionHostConnection] New connection established.
[2022-10-14 13:22:15.784] [remoteagent] [info] [127.0.0.1][55c06ec9][ExtensionHostConnection] <1529> Launched Extension Host Process.
[2022-10-14 13:22:19.162] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateIcon (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:3046)","    at Object.call (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-14 13:22:40.680] [remoteagent] [info] [127.0.0.1][4a462357][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-14 13:22:40.694] [remoteagent] [info] [127.0.0.1][55c06ec9][ExtensionHostConnection] <1529> Extension Host Process exited with code: 0, signal: null.
[2022-10-14 13:22:40.694] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-10-14 13:22:45.593] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-10-14 13:22:45.593] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-10-14 13:22:45.700] [remoteagent] [info] [127.0.0.1][288ac0dc][ManagementConnection] New connection established.
[2022-10-14 13:22:45.700] [remoteagent] [info] [127.0.0.1][d33ef77d][ExtensionHostConnection] New connection established.
[2022-10-14 13:22:45.709] [remoteagent] [info] [127.0.0.1][d33ef77d][ExtensionHostConnection] <1659> Launched Extension Host Process.
[2022-10-14 13:22:47.981] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-14 13:27:45.592] [remoteagent] [info] New EH opened, aborting shutdown
[2022-10-14 13:33:59.699] [remoteagent] [info] [127.0.0.1][c5d2825c][ManagementConnection] New connection established.
[2022-10-14 13:33:59.712] [remoteagent] [info] [127.0.0.1][31a30ccd][ExtensionHostConnection] New connection established.
[2022-10-14 13:33:59.737] [remoteagent] [info] [127.0.0.1][31a30ccd][ExtensionHostConnection] <1906> Launched Extension Host Process.
[2022-10-14 13:34:02.172] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-14 13:34:07.924] [remoteagent] [info] [127.0.0.1][c5d2825c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-14 13:34:07.946] [remoteagent] [info] [127.0.0.1][31a30ccd][ExtensionHostConnection] <1906> Extension Host Process exited with code: 0, signal: null.
[2022-10-14 14:03:43.896] [remoteagent] [info] [127.0.0.1][6f9c1015][ManagementConnection] New connection established.
[2022-10-14 14:03:43.922] [remoteagent] [info] [127.0.0.1][40b674d5][ExtensionHostConnection] New connection established.
[2022-10-14 14:03:43.940] [remoteagent] [info] [127.0.0.1][40b674d5][ExtensionHostConnection] <2863> Launched Extension Host Process.
[2022-10-14 14:03:48.678] [remoteagent] [info] [127.0.0.1][6f9c1015][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-14 14:03:48.694] [remoteagent] [info] [127.0.0.1][40b674d5][ExtensionHostConnection] <2863> Extension Host Process exited with code: 0, signal: null.
[2022-10-14 14:03:53.096] [remoteagent] [info] [127.0.0.1][d602f9ec][ManagementConnection] New connection established.
[2022-10-14 14:03:53.116] [remoteagent] [info] [127.0.0.1][18f4b8ae][ExtensionHostConnection] New connection established.
[2022-10-14 14:03:53.141] [remoteagent] [info] [127.0.0.1][18f4b8ae][ExtensionHostConnection] <3006> Launched Extension Host Process.
[2022-10-14 14:03:55.481] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-14 14:03:59.681] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch on '//proc/1503/task/3043/attr' failed: No such file or directory (EUNKNOWN) (path: /)
[2022-10-14 14:03:59.681] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '//proc/1503/task/3043/attr' failed: No such file or directory
[2022-10-14 14:04:00.779] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch on '//proc/3056/net/netfilter' failed: No such file or directory (EUNKNOWN) (path: /)
[2022-10-14 14:04:00.779] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '//proc/3056/net/netfilter' failed: No such file or directory
[2022-10-14 14:04:01.362] [remoteagent] [error] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /)
[2022-10-14 14:10:42.147] [remoteagent] [info] [127.0.0.1][288ac0dc][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-14 14:10:42.248] [remoteagent] [info] [127.0.0.1][d33ef77d][ExtensionHostConnection] <1659> Extension Host Process exited with code: 0, signal: null.
